services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            #$projectDir: '%kernel.project_dir%'

    Markocupic\ContaoTinymcePluginBuilderBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Resources}




